### ISSUE TITLE
SnapshotConnector for generating Ebook?

### ISSUE THREAD

**Issue by John2496** [anqxyr/pyscp#1]
Can you please include the SnapshotConnector module needed to generate the Ebook? I'd like to generate the MOBI format with greyscale images compressed under 64kb (not sure if this is possible yet). Thanks!

**Comment by anqxyr** [comment]
I haven't really done a good job at keeping this repo up to date. I'll see about pushing the latest code in the next couple of days. Then we'll see where mobi fits into it.

**Comment by anqxyr** [comment]
Here is the latest code that handles ebook generation: https://github.com/anqxyr/pyscp_ebooks

Specifically, if you want it to generate something other than .epub, you should replace the `book` attribute of the ebook builder, here:
https://github.com/anqxyr/pyscp_ebooks/blob/master/pyscp_ebooks/builder.py#L34

With something with the same api as the ebook module, here:
https://github.com/anqxyr/pyscp_ebooks/blob/master/pyscp_ebooks/epub.py

I hope this answers your question.

**Comment by John2496** [comment]
Awesome, thanks for the push! I'm looking into a strange issue that occurs ~5min into creating a snapshot (also happened with old version of the code). Running this in python 3.4 on OS X (El Capitan). Please let me know if I'm missing something obvious. Thanks!

take-snapshot.py (executed via `python3.4 take-snapshot.py`):

```
import pyscp

wiki = pyscp.wikidot.Wiki('www.scp-wiki.net')

creator = pyscp.snapshot.SnapshotCreator('snapshot_file_4.db')
creator.take_snapshot(wiki, forums=False)
```

Stack trace:

```
Traceback (most recent call last):
  File "take-snapshot.py", line 6, in <module>
    creator.take_snapshot(wiki, False)#forums=False)
  File "/Users/John/Desktop/pyscp/pyscp/snapshot.py", line 234, in take_snapshot
    self._save_all_pages()
  File "/Users/John/Desktop/pyscp/pyscp/snapshot.py", line 254, in _save_all_pages
    for _ in self.pool.map(self._save_page, self.wiki.list_pages()):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/_base.py", line 549, in result_iterator
    yield future.result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/John/Desktop/pyscp/pyscp/utils.py", line 50, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/John/Desktop/pyscp/pyscp/utils.py", line 73, in ignore
    return call()
  File "/Users/John/Desktop/pyscp/pyscp/utils.py", line 31, in __call__
    return self.func(*self.args, **self.kwargs)
  File "/Users/John/Desktop/pyscp/pyscp/snapshot.py", line 272, in _save_page
    dict(i, page=page._id) for i in data)
  File "/Users/John/Desktop/pyscp/pyscp/orm.py", line 52, in insert_many
    chunk = list(islice(data_iter, 500))
  File "/Users/John/Desktop/pyscp/pyscp/snapshot.py", line 272, in <genexpr>
    dict(i, page=page._id) for i in data)
  File "/Users/John/Desktop/pyscp/pyscp/orm.py", line 61, in convert_to_id
    for row in data:
TypeError: vars() argument must have __dict__ attribute
```

**Comment by anqxyr** [comment]
From the traceback, it looks like either `.history` or `.votes` for some page has some weird stuff in it that shouldn't be in there. I can't really think of anything that may have caused it.

Try running the following code and see what ends up in the log:

``` python
import pyscp
import logging
import requests

log = logging.getLogger(__name__)


class SnapshotCreator(pyscp.snapshot.SnapshotCreator):

    @pyscp.utils.ignore(requests.HTTPError)
    def _save_page(self, page):
        for i in page.history + page.votes:
            try:
                vars(i)
            except TypeError:
                log.error(page)
                log.error(i)
        super()._save_page(page)

pyscp.utils.default_logging(debug=False)

wiki = pyscp.wikidot.Wiki('www.scp-wiki.net')

creator = SnapshotCreator('snapshot_file_4.db')
creator.take_snapshot(wiki, forums=False)
```

The log should appear in a `pyscp.log` file in the directory from which you run the script.

**Comment by John2496** [comment]
Ah thanks! I traced the error back to the map function (in this case `map(vars, images)`). I'm able to consistently replicate the error in `_save_meta()` by iterating through `images`. The objects are missing `__dict__` for some reason. Please see below...

Modified `snapshot.py` (jump straight to `_save_meta`):

``` python
    def take_snapshot(self, wiki, forums=False):
        """Take new snapshot."""
        self.wiki = wiki
        #self._save_all_pages()
        #if forums:
        #    self._save_forums()
        if 'scp-wiki' in self.wiki.site:
            self._save_meta()
        orm.queue.join()
        self._save_cache()
        orm.queue.join()
        log.info('Snapshot succesfully taken.')

    def _save_meta(self):
        orm.create_tables(
            'Image', 'ImageStatus', 'Override', 'OverrideType')
        licenses = {
            'PERMISSION GRANTED', 'BY-NC-SA CC', 'BY-SA CC', 'PUBLIC DOMAIN'}
        images = [i for i in self.wiki.list_images() if i.status in licenses]
        self.ibar = utils.ProgressBar(
            'SAVING IMAGES'.ljust(20), len(images))
        self.ibar.start()
        data = list(self.pool.map(self._save_image, images))
        self.ibar.stop()
        #####images = orm.ImageStatus.convert_to_id(
        #####    map(vars, images), key='status')

        ############## See below ###############

        # For some reason __dict__ is undefined
        # print(images[0].__dict__)

        # Throws the error - AttributeError: 'Image' object has no attribute '__dict__'
        # print(vars(images[0]))

        # Which causes the fail here
        for x in images:
            print(x)

        orm.Image.insert_many(
            dict(i, data=d) for i, d in zip(images, data) if d)
        overs = orm.User.convert_to_id(
            map(vars, self.wiki.list_overrides()))
        overs = orm.OverrideType.convert_to_id(overs, key='type')
        orm.Override.insert_many(overs)
```

**Comment by anqxyr** [comment]
I think this is the cause of the error: https://stackoverflow.com/questions/34166469/did-something-about-namedtuple-change-in-3-5-1

I'll try to make the necessary changes over the weekend.

**Comment by John2496** [comment]
Nice find! I replaced occurences of `map(vars,` with `map(lambda x: x._asdict() if hasattr(x, '_asdict') else vars(x),` in `snapshot.py` seems to have resolved the issue.

Edit: Updated code

**Comment by anqxyr** [comment]
The repo's code has been updated with a permanent fix for the issue.
